### ISSUE TITLE
This doesn't work with .cjsx file extension

### ISSUE THREAD

**Issue by ragesoss** [ragesoss/jest-react-coffeescript#1]
@redice Thanks for your version, which I got working and found helpful! The one problem for my project is that, while it works fine for cjsx modules with the .coffee extension, it doesn't work if the file is .cjsx.

Do you know how to get it to work with .cjsx files (as in this fork)?

**Comment by redice** [comment]
@ragesoss I modify the config setting in package.json, it works well in my project with jest-cli 0.5.10.

**Comment by ragesoss** [comment]
@redice thank you!
